### PR TITLE
replace all config.env with .env for consistency 

### LINKED ISSUE #14: config.env >> .env (standardise!)
https://github.com/dwyl/learn-environment-variables/#3-use-a-configenv-file-locally-which-you-can-gitignore
should be updated to `.env` asap to avoid confusing people.

### PR DESCRIPTION
**Pull request by nelsonic**
fixes #14

### CODE REVIEW

**Comment by iteles** [comment]
Nice :+1:

**Comment by jackcarlisle** [comment]
👍

**Comment by jackcarlisle** [comment]
@iteles beat me to it 😏

**Comment by nelsonic** [comment]
@iteles / @jackcarlisle thanks. 👍 
@Cleop reminded me of this ... 😉

**Pull request merged**
